var menudata={children:[
{text:'Титульная страница',url:'index.html'},
{text:'Пространства имен',url:'namespaces.html',children:[
{text:'Пространства имен',url:'namespaces.html'}]},
{text:'Классы',url:'annotated.html',children:[
{text:'Классы',url:'annotated.html'},
{text:'Алфавитный указатель классов',url:'classes.html'},
{text:'Иерархия классов',url:'hierarchy.html'},
{text:'Члены классов',url:'functions.html',children:[
{text:'Указатель',url:'functions.html',children:[
{text:'_',url:'functions.html#index__'},
{text:'a',url:'functions.html#index_a'},
{text:'b',url:'functions.html#index_b'},
{text:'c',url:'functions.html#index_c'},
{text:'d',url:'functions.html#index_d'},
{text:'e',url:'functions.html#index_e'},
{text:'f',url:'functions.html#index_f'},
{text:'h',url:'functions.html#index_h'},
{text:'i',url:'functions.html#index_i'},
{text:'l',url:'functions.html#index_l'},
{text:'m',url:'functions.html#index_m'},
{text:'o',url:'functions.html#index_o'},
{text:'p',url:'functions.html#index_p'},
{text:'r',url:'functions.html#index_r'},
{text:'s',url:'functions.html#index_s'},
{text:'u',url:'functions.html#index_u'},
{text:'v',url:'functions.html#index_v'},
{text:'z',url:'functions.html#index_z'}]},
{text:'Функции',url:'functions_func.html',children:[
{text:'c',url:'functions_func.html#index_c'},
{text:'d',url:'functions_func.html#index_d'},
{text:'e',url:'functions_func.html#index_e'},
{text:'f',url:'functions_func.html#index_f'},
{text:'i',url:'functions_func.html#index_i'},
{text:'l',url:'functions_func.html#index_l'},
{text:'m',url:'functions_func.html#index_m'},
{text:'o',url:'functions_func.html#index_o'},
{text:'r',url:'functions_func.html#index_r'},
{text:'s',url:'functions_func.html#index_s'}]},
{text:'Переменные',url:'functions_vars.html',children:[
{text:'_',url:'functions_vars.html#index__'},
{text:'a',url:'functions_vars.html#index_a'},
{text:'b',url:'functions_vars.html#index_b'},
{text:'c',url:'functions_vars.html#index_c'},
{text:'d',url:'functions_vars.html#index_d'},
{text:'h',url:'functions_vars.html#index_h'},
{text:'i',url:'functions_vars.html#index_i'},
{text:'l',url:'functions_vars.html#index_l'},
{text:'m',url:'functions_vars.html#index_m'},
{text:'o',url:'functions_vars.html#index_o'},
{text:'p',url:'functions_vars.html#index_p'},
{text:'r',url:'functions_vars.html#index_r'},
{text:'s',url:'functions_vars.html#index_s'},
{text:'u',url:'functions_vars.html#index_u'},
{text:'v',url:'functions_vars.html#index_v'},
{text:'z',url:'functions_vars.html#index_z'}]}]}]},
{text:'Файлы',url:'files.html',children:[
{text:'Файлы',url:'files.html'}]}]}
